# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Pioneer.rekordbox
PackageVersion: 5.8.7
PackageLocale: en-US
Publisher: AlphaTheta
PackageName: rekordbox5
License: sofrware agreement
ShortDescription: rekordboxは、クラウドを用いた楽曲管理からDJパフォーマンスまでを統合したDJアプリケーションです。
ManifestType: defaultLocale
ManifestVersion: 1.6.0
