# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Dwango.nico.nair
PackageVersion: 1.1.20240216-1
PackageLocale: Ja-JP
Publisher: Dwango
PublisherUrl: https://n-air-app.nicovideo.jp/
PublisherSupportUrl: https://github.com/n-air-app/n-air-app/issues
PrivacyUrl: https://dwango.co.jp/terms/privacy/
Author: koizuka
PackageName: N-AIR
PackageUrl: https://github.com/n-air-app/n-air-app
License: GPL-3.0 license
LicenseUrl: https://github.com/n-air-app/n-air-app?tab=GPL-3.0-1-ov-file#readme
Copyright: DWANGO Co., Ltd.
CopyrightUrl: https://dwango.co.jp/
ShortDescription: 雑談・ゲーム実況などあらゆるスタイルで配信できる無料ソフトウェアです
Description: N AirはStreamlabs Desktopをベースにした、生放送に便利な機能が豊富に組み込まれた高画質配信ソフトウェアです。Webカメラやゲームなどの映像をニコニコ生放送などのあらゆる配信サービスに配信できます。かんたんな操作と自由な発想で、自分だけのライブ配信を始めましょう。
Moniker: obs
Tags:
- streamlabs
- niconico
- dwango
- live
- nicovideo
ReleaseNotes: ニコニコ生放送の最大放送時間を6時間から24時間に変更 (#722)
ReleaseNotesUrl: https://github.com/n-air-app/n-air-app/releases/tag/v1.1.20240216-1
ManifestType: defaultLocale
ManifestVersion: 1.6.0
